name: acme

version: '1.0'
config-version: 2

require-dbt-version: ">=0.16.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

seeds:
  quote_columns: false

models:
  transient: true
